

export const workersPath = '/dashboard/workers'
export const familyCodePath = '/dashboard/productFamily'
export const scannedArticlesPath = '/dashboard/scannedArticles'
export const userPath = '/dashboard/user'
export const stockPath = '/dashboard/stock'
export const affectationsPath = '/dashboard/affectations'
export const affectationPermisionsPath = '/dashboard/user/affectationPermisions'
export const groupsPermissionsPath = '/dashboard/groupsPermissions'
export const sessionsPath = '/dashboard/session'
export const sessionGroupsPath = '/dashboard/session/groups'
export const sessionWorkersPath = '/dashboard/session/workers'
export const inventoryPath = '/dashboard/inventory'
export const sessionRecordPath = '/dashboard/sessionRecord'
export const importsPath = '/dashboard/settings/imports'


export const editWorkersPath = '/dashboard/workers/:id/edit'
export const editFamilyCodePath = '/dashboard/productFamily/:id/edit'
export const editScannedArticlesPath = '/dashboard/scannedArticles/:id/edit'
export const editUserPath = '/dashboard/user/:id/edit'
export const editStockPath = '/dashboard/stock/:id/edit'
export const editAffectationsPath = '/dashboard/affectations/:id/edit'
export const editAffectationPermisionsPath = '/dashboard/user/affectationPermisions/:id/edit'
export const editGroupsPermissionsPath = '/dashboard/groupsPermissions/:id/edit'
export const editSessionsPath = '/dashboard/session/:id/edit'
export const editSessionGroupsPath = '/dashboard/session/groups/:id/edit'
export const editSessionWorkersPath = '/dashboard/session/workers/:id/edit'
export const editInventoryPath = '/dashboard/inventory/:id/edit'
export const editSessionRecordPath = '/dashboard/sessionRecord/:id/edit'



export const createWorkersPath = '/dashboard/workers/new'
export const createFamilyCodePath = '/dashboard/productFamily/new'
export const createScannedArticlesPath = '/dashboard/scannedArticles/new'
export const createUserPath = '/dashboard/user/new'
export const createStockPath = '/dashboard/stock/new'
export const createAffectationsPath = '/dashboard/affectations/new'
export const createAffectationPermisionsPath = '/dashboard/user/affectationPermisions/new'
export const createGroupsPermissionsPath = '/dashboard/groupsPermissions/new'
export const createSessionsPath = '/dashboard/session/new'
export const createSessionGroupsPath = '/dashboard/session/groups/new'
export const createSessionWorkersPath = '/dashboard/session/workers/new'
export const createInventoryPath = '/dashboard/inventory/new'
export const createSessionRecordPath = '/dashboard/sessionRecord/new'
