

export const workersPath = '/workers'
export const familyCodePath = '/familyCode'
export const scannedArticlesPath = '/scannedArticles'
export const userPath = '/user'
export const stockPath = '/stock'
export const affectationsPath = '/affectations'
export const affectationPermisionsPath = '/affectationPermisions'
export const groupsPermissionsPath = '/groupsPermissions'
export const sessionsPath = '/sessions'
export const sessionGroupsPath = '/sessionGroups'
export const sessionWorkersPath = '/sessionWorkers'
export const inventoryPath = '/inventory'
export const sessionRecordPath = '/sessionRecord'


export const editWorkersPath = '/workers/:id/edit'
export const editFamilyCodePath = '/familyCode/:id/edit'
export const editScannedArticlesPath = '/scannedArticles/:id/edit'
export const editUserPath = '/user/:id/edit'
export const editStockPath = '/stock/:id/edit'
export const editAffectationsPath = '/affectations/:id/edit'
export const editAffectationPermisionsPath = '/affectationPermisions/:id/edit'
export const editGroupsPermissionsPath = '/groupsPermissions/:id/edit'
export const editSessionsPath = '/sessions/:id/edit'
export const editSessionGroupsPath = '/sessionGroups/:id/edit'
export const editSessionWorkersPath = '/sessionWorkers/:id/edit'
export const editInventoryPath = '/inventory/:id/edit'
export const editSessionRecordPath = '/sessionRecord/:id/edit'



export const createWorkersPath = '/workers/new'
export const createFamilyCodePath = '/familyCode/new'
export const createScannedArticlesPath = '/scannedArticles/new'
export const createUserPath = '/user/new'
export const createStockPath = '/stock/new'
export const createAffectationsPath = '/affectations/new'
export const createAffectationPermisionsPath = '/affectationPermisions/new'
export const createGroupsPermissionsPath = '/groupsPermissions/new'
export const createSessionsPath = '/sessions/new'
export const createSessionGroupsPath = '/sessionGroups/new'
export const createSessionWorkersPath = '/sessionWorkers/new'
export const createInventoryPath = '/inventory/new'
export const createSessionRecordPath = '/sessionRecord/new'
