/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as affectation from "../affectation";
import type * as cache from "../cache";
import type * as helpers_createHelpers from "../helpers/createHelpers";
import type * as helpers_isAuthenticated from "../helpers/isAuthenticated";
import type * as helpers_statusCodes from "../helpers/statusCodes";
import type * as helpers_updateHelpers from "../helpers/updateHelpers";
import type * as helpers_utility from "../helpers/utility";
import type * as http from "../http";
import type * as importData from "../importData";
import type * as inventory from "../inventory";
import type * as permissions from "../permissions";
import type * as productFamily from "../productFamily";
import type * as session from "../session";
import type * as sessionGroup from "../sessionGroup";
import type * as sessionWorker from "../sessionWorker";
import type * as stock from "../stock";
import type * as user from "../user";
import type * as workers from "../workers";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  affectation: typeof affectation;
  cache: typeof cache;
  "helpers/createHelpers": typeof helpers_createHelpers;
  "helpers/isAuthenticated": typeof helpers_isAuthenticated;
  "helpers/statusCodes": typeof helpers_statusCodes;
  "helpers/updateHelpers": typeof helpers_updateHelpers;
  "helpers/utility": typeof helpers_utility;
  http: typeof http;
  importData: typeof importData;
  inventory: typeof inventory;
  permissions: typeof permissions;
  productFamily: typeof productFamily;
  session: typeof session;
  sessionGroup: typeof sessionGroup;
  sessionWorker: typeof sessionWorker;
  stock: typeof stock;
  user: typeof user;
  workers: typeof workers;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
